### ISSUE TITLE
unity csi 1.4 snapshots

### ISSUE THREAD

**Issue by encore0** [dell/storage-plugin-docs#11]
According to the TME

The documentation is wrong here ☹ These are old and incompatible CRDs
To be honest, I always install the CRD with the csi-install script.sh --snapshot-crd option.

Also, the generic external-snapshotter image we point to is wrong.
When you install the snapshotter you should use : 
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

**Comment by coulof** [comment]
With the recent releases, the links have been updated to proper versions.
