### ISSUE TITLE
Unity 1.4 csi readme

### ISSUE THREAD

**Issue by encore0** [dell/storage-plugin-docs#9]
Before you begin
•	You must have the downloaded files, including the Helm chart from the source git repository, ready for this procedure.
In the product guide we used to have the clone command. This would be useful

“Copy the csi-unity/values.yaml into a file named myvalues.yaml in the same directory of csi-install.sh, to customize settings for installation.”
The path for the values.yaml should be
csi-unity/helm/csi-unity

“Create an empty secret by navigating to helm folder that contains emptysecret.yaml file and running the kubectl create -f emptysecret.yaml command.”
We should add the path to this file

**Comment by Sakshi-dell** [comment]
This issue is resolved in latest PR merge https://github.com/dell/storage-plugin-docs/pull/19
@encore0 Can you confirm the same and close this issue?

**Comment by shanmydell** [comment]
This issue is resolved, Please reopen in case of any discrepancy

**Comment by encore0** [comment]
thanks
    On Tuesday, May 18, 2021, 08:12:21 AM CDT, shanmydell ***@***.***> wrote:  
 
 


This issue is resolved, Please reopen in case of any discrepancy
